name: 'Packer with Ansible'
description: 'GitHub Action to run Packer with Ansible'
author: 'Christopher Chow <chris@chowops.com>'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  color: blue
  icon: package
