name: 'Build'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2

      - name: 'Build and push docker image'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "christophersjchow"
          password: ${{ secrets.GHCR_TOKEN }}
          repository: chowops/action-packer-ansible
          tags: latest
